[package]
name = "moon-phase-simulator"
repository = "https://github.com/MaarifaMaarifa/MoonPhaseSimulator"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
strip = true
codegen-units = 1
